app:
  url: http://baidu.com
  name: baidu-dev
  version: 566

#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:20000/eureka