app:
  url: http://application-prod.com
  name: application-prod
  version: 208

management:
  endpoints:
    web:
      exposure:
#        include: "refresh,info,health,busrefresh"
        include: "*"